### PR TITLE
Update base package dependency

### PR DESCRIPTION
**Pull request by jasonvarga**
As per #7 - this just updates the composer dependency. Everything that I used seemed to work just fine. (I just used the basic OAuth flow. No refreshing tokens, etc). Tests still pass. Not sure if anything else needs changing.

### CODE REVIEW

**Comment by adam-paterson** [comment]
@jasonvarga The build is breaking at the moment because in `2.*` League have dropped support of `5.5`. Can you update that too please?

**Comment by jasonvarga** [comment]
There we go.

**Comment by adam-paterson** [comment]
@jasonvarga Thank you, I'm going to merge this into a 2.0 branch. I've found a few more changes I need to bring across which I'll do asap.

**Comment by jasonvarga** [comment]
Thanks very much for being so on top of this!

**Comment by adam-paterson** [comment]
@jasonvarga No problem, thanks for using the package! Version `2.0.0` has been tagged now.

**Pull request merged**
